server.port: 8081

spring:
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:hydra;DB_CLOSE_DELAY=-1

logging:
  level:
    de.coding.kata.nim: DEBUG

# Game specific settings
game:
  minMatches: 1
  maxMatches: 3
  initialMatchCount: 13
  computer.name: Computer